### ISSUE TITLE
Will it work with angular@core 4.2.4?

### ISSUE THREAD

**Issue by velusgautam** [joshterrill/ng2-cli-sweetalert2#10]
Will it work with angular@core 4.2.4?

**Comment by joshterrill** [comment]
It should, though I would recommend using the official sweetalert 2 library, which can be found here: https://limonte.github.io/sweetalert2/

The reason I created this repo was because their official repo did not support typescript. Now it does, so I stopped maintaining this repo.

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
