### ISSUE TITLE
There could be any explanation about how to use it?

### ISSUE THREAD

**Issue by davidrock** [joshterrill/ng2-cli-sweetalert2#11]
Please add some instructions about how to use it.
I tried here but I am getting this error:

`win.Sweetalert2 is not a function`

My code is something like this:
```
constructor(private _swal: SweetAlertService){
}
```

```
ngOnInit() {
this._swal.alert({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!',
      cancelButtonText: 'No, cancel!',
      confirmButtonClass: 'btn btn-success',
      cancelButtonClass: 'btn btn-danger',
      buttonsStyling: false
    });
}

```

**Comment by joshterrill** [comment]
Please use the official sweet alert 2 repo as it supports typescript now: https://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by joshterrill** [comment]
@limonte Thanks, I've updated my readme with the new link.
