### ISSUE TITLE
npm release is out of date

### ISSUE THREAD

**Issue by KyleCartmell** [joshterrill/ng2-cli-sweetalert2#4]
The last NPM publish occurred on October 4th. Can the current master branch be published to NPM and a corresponding release be created on github?

**Comment by joshterrill** [comment]
Yes I will do it when I get back to work in 20 minutes. Nice catch.

**Comment by joshterrill** [comment]
Done.

**Comment by KyleCartmell** [comment]
Thanks @joshterrill !
