### ISSUE TITLE
Warn type should be 'warning' and not 'warn'

### ISSUE THREAD

**Issue by pajaroblanco** [joshterrill/ng2-cli-sweetalert2#6]
The SweetAlertService.warn method incorrectly sets type: 'warn' instead of type: 'warning' and SweetAlert2 throws the following exception: 

> SweetAlert2: Unknown alert type: warn

**Comment by joshterrill** [comment]
Fixed it in the latest commit. Thanks.

**Comment by pajaroblanco** [comment]
Awesome, thank you!
