### ISSUE TITLE
Cannot find module 'ng2-cli-sweetalert2'

### ISSUE THREAD

**Issue by Lawrence23** [joshterrill/ng2-cli-sweetalert2#7]
I am ng2-cli-sweetalert2 in my project. Even though the functionalities are all working, I am getting this error

`Cannot find module 'ng2-cli-sweetalert2'`

Because of this, I am not able to create my build file. Can anyone help me out here?

**Comment by fvozar** [comment]
This helped me:

```
import { SweetAlertService } from 'ng2-cli-sweetalert2/src/index';
```

**Comment by joshterrill** [comment]
The official sweetalert2 library now supports type script, so this library is no longer needed. I'm going to be updating the README now. 

Here's the official library: https://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
