### ISSUE TITLE
The "swal2-container swal2-fade" stays in the DOM

### ISSUE THREAD

**Issue by jaronwright** [joshterrill/ng2-cli-sweetalert2#8]
When the container closes the element stays in the dom and does not go away. It has a z-index leaving my site useless

**Comment by joshterrill** [comment]
Please use the official sweetalert2 library, which now supports typescript and works with the angular-cli. It can be found here: https://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
